 name: Test Outputs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Set color
        id: color-selector
        run: echo "SELECTED_COLOR=green" >> "$GITHUB_OUTPUT"
      - name: Get color
        env:
          SELECTED_COLOR: ${{ steps.color-selector.outputs.SELECTED_COLOR }}
        run: echo "The selected color is $SELECTED_COLOR"

      - name: Set color
        id: color-selector-dash
        run: echo "-SELECTED_COLOR=yellow" >> "$GITHUB_OUTPUT"
      - name: Get color
        env:
          SELECTED_COLOR: ${{ steps.color-selector-dash.outputs['-SELECTED_COLOR'] }}
        run: echo "The selected color is $SELECTED_COLOR"

      - name: Set color
        id: color-selector-at
        run: echo "@SELECTED_COLOR=red" >> "$GITHUB_OUTPUT"
      - name: Get color
        env:
          SELECTED_COLOR: ${{ steps.color-selector-at.outputs['@SELECTED_COLOR'] }}
        run: echo "The selected color is $SELECTED_COLOR"

      - name: Set color
        id: color-selector-slash
        run: echo "SELECTED_COLOR/boop=blue" >> "$GITHUB_OUTPUT"
      - name: Get color
        env:
          SELECTED_COLOR: ${{ steps.color-selector-slash.outputs['SELECTED_COLOR/boop'] }}
        run: echo "The selected color is $SELECTED_COLOR"

      - name: Set color
        id: color-selector-all
        run: echo "@SELECTED_COLOR/boop=black" >> "$GITHUB_OUTPUT"
      - name: Get color
        env:
          SELECTED_COLOR: ${{ steps.color-selector-all.outputs['@SELECTED_COLOR/boop'] }}
        run: echo "The selected color is $SELECTED_COLOR"
